# url path of genie
playlist_origin_url: https://www.genie.co.kr/playlist/popular?sortOrd=RDD
playlist_url: https://www.genie.co.kr/playlist/detailView?plmSeq=

# file path
out_dir: outputs/
log_dir: outputs/logs/

# csv file name
pl_filename: pl_info.csv
song_filename: song_info.csv

# concat file name
pl_concat: playlists.csv
song_concat: songs.csv

# img resize option
img_resize: 140
max_resize: 600

# retrival scope
start_idx: 15625
end_idx:
