# url path of genie
song_detail_url: https://www.genie.co.kr/detail/songInfo?xgnm=

# file path
out_dir: outputs/
log_dir: logs/

# csv file name
song_detail_filename: song_detail.csv

# base song info file name
song_info_filename: song_info.csv
