# url path of genie
song_detail_url: https://www.genie.co.kr/detail/songInfo?xgnm=

# file path
out_dir: outputs/
log_dir: logs/

# csv file name
song_detail_filename: sample_song_detail_0.csv

# base song info file name
song_info_filename: songs_v4_0.csv
