# url path of genie
album_detail_url: https://www.genie.co.kr/detail/albumInfo?axnm=

# file path
out_dir: outputs/

# csv file name
album_info_filename: album_info_0717.csv

# base song info file name
song_info_filename: 1_5_song_info.csv

# img resize option
img_resize: 244
max_resize: 600
