# url path of genie
album_detail_url: https://www.genie.co.kr/detail/albumInfo?axnm=

# file path
out_dir: outputs/

# csv file name
album_info_filename: album_info_0717.csv

# base song info file name
song_info_filename: 15625_15632_song_info.csv
