# url path of genie
song_detail_url: https://www.genie.co.kr/detail/songInfo?xgnm=

# file path
out_dir: outputs/

# csv file name
song_detail_filename: song_detail_0717.csv

# base song info file name
song_info_filename: 15624_15632_song_info.csv
